### ISSUE TITLE
Feature Request: create catonaut app npm package

### ISSUE THREAD

**Issue by mAmineChniti** [AminoffZ/catonaut#2]
I think catonaut would really benefit from having an npm cli package that lets developers create/initialize a new catonaut project from the terminal the same way they'd do `npx create-react-app my-app` or `bunx create t3-app@latest`, etc....

**Comment by AminoffZ** [comment]
Interesting suggestion, I have not looked into how to do this yet. Something to look at for sure.

**Comment by mAmineChniti** [comment]
I had a couple of free hours today and i've been able to create a cli tool to be used with npx create-catonaut [appName] when published i'd be happy to share my work with you'd if you'd be kind enough to initialize me an empty repository to fork and and send you a pull request on it, maybe call it create-catonaut and just have an empty README.md in it

**Comment by AminoffZ** [comment]
Awesome, excited to see it!
https://github.com/AminoffZ/create-catonaut
