### ISSUE TITLE
TailwindCSS Not Working

### ISSUE THREAD

**Issue by harbar20** [AminoffZ/catonaut#5]
I'm trying to setup TailwindCSS with this extension template but it doesn't seem to work. My `astro.config.mjs` looks like this:
```js
import { defineConfig } from "astro/config";
import tailwind from "@astrojs/tailwind";

// https://astro.build/config
export default defineConfig({
    build: {
        assets: "app",
    },
    integrations: [tailwind()],
});
```

and my `tailwind.config.cjs` looks like this:
```js
/** @type {import('tailwindcss').Config} */
module.exports = {
	content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
	theme: {
		extend: {},
	},
	plugins: [],
}
```

when I build the project, it generates everything as normal, except my `dist` folder structure looks like this:
<img width="252" alt="Screenshot 2024-01-03 at 2 33 42 PM" src="https://github.com/AminoffZ/catonaut/assets/30803341/179367eb-137c-4494-9896-671955cb647a">

The popup when I run it in dev mode looks just fine, but when I try to insert the HTML into a page, it doesn't show up, and I'm not sure why.

Any ideas what might be causing this?

**Comment by AminoffZ** [comment]
Hi, did you have it working before adding tailwind?

**Comment by harbar20** [comment]
I did! I tested it with inline styles and it worked perfectly.

**Comment by AminoffZ** [comment]
> The popup when I run it in dev mode looks just fine, but when I try to insert the HTML into a page, it doesn't show up, and I'm not sure why.

What is the HTML you are trying to insert where? Are you using the content.ts script to manipulate the DOM and that's not working? If it's not too private, sharing your some of your code might be helpful.

**Comment by harbar20** [comment]
Apologies for the delay. Yes, I'm using the `content.ts` script to manipulate the DOM. Here's the HTML:
```html
<div class="bg-blue-500">
    <p>
        Testing testing 123 456
        <br>
        789
    </p>
</div>
```

and here's the `content.ts`:
```ts
// Credit to https://stackoverflow.com/a/16336073
fetch(chrome.runtime.getURL("index.html"))
    .then((r) => r.text())
    .then((html) => {
        const placeholder = document.createElement("div");
        placeholder.innerHTML = html;
        const node = placeholder.firstElementChild;

        if (node == null) {
            return;
        }

        node.classList.add("wc-ext-container");

        document.body.insertBefore(node, document.body.firstChild);
    });
```

I added `wc-ext-container` to the `classList` there just so I could extremely easily identify the `div` in the Inspect element on the page.

**Comment by harbar20** [comment]
Hi! Just wanted to bump this. Do you know what's going on?

**Comment by AminoffZ** [comment]
Hi, sorry for the delay. If I understand correctly you are attempting to create an html element styled by Tailwind and then append that to a page's DOM?

**Comment by AminoffZ** [comment]
I'm gonna close this as not planned. Feel free to reopen.

**Comment by AminoffZ** [comment]
I'm gonna close this as not planned. Feel free to reopen.
